apps/catalog/urls.py
from django.conf.urls import patterns, include, url
from apps.core.shortcuts import direct_to_template

urlpatterns = patterns(
    'apps.catalog.views',
    url(r'^$', 'index', name='index'),
    url(r'services/$', 'service_list', name='service-list'),
    url(r'services/specials/(?:(?P<service_name>\w+)/)?$', 'all_specials',
        name='all-specials'),
    url(r'services/(?P<service_pk>\d+)/$', 'catalog_list',
        name='catalog-list'),
    url(r'services/(?P<codename>[\w\d\.\-\_]+)/$', 'catalog_list',
        name='catalog-list'),
    url(r'services/(?P<codename>[\w\d\.\-\_]+)/specials/$',
        'catalog_list', {'is_special': True},
        name='catalog-list-specials'),
    url(r'service/(?P<pk>\d+)/$', 'service_page', name='service-page'),
    url(r'service/(?P<pk>\d+)/category/(?P<category_pk>\d+)/$',  # (?P<title>[\w\d\s\-\_\.\ ,]+)/$',
        'service_page', name='service-page'),
    url(r'service/(?P<pk>\d+)/rating/$',
        'service_rating', name='service-rating'),
    url(r'service/(?P<pk>\d+)/about/$',
        'service_about', name='service-about'),
    url(r'service/(?P<pk>\d+)/specials/$',
        'service_specials', name='service-specials'),
    url(r'service/specials/(?P<pk>\d+)/$',
        'service_partner_specials',
        name='service-partner-specials'),
    url(r'service/specials/(?P<pk>\d+)/edit/$',
        'special_add', name='special-edit'),
    url(r'service/specials/(?P<pk>\d+)/delete/$',
        'special_del', name='special-del'),
    url(r'service/specials/add/$',
        'special_add', name='special-add'),
    url(r'service/orders/notconfirmed/$', 'service_orders_nc',
        name='service-orders'),
    url(r'service/orders/$', 'service_orders',
        name='service-orders-confirmed'),
    url(r'service/orders/(?P<pk>\d+)/info/$', 'service_order_info',
        name='service-order-info'),
    url(r'service/orders/(?P<pk>\d+)/update/$', 'service_order_update',
        name='service-order-update'),
    url(r'containers/$', 'container_list', name='container-list'),
    url(r'containers/(?P<pk>\d+)/$', 'container', name='container'),
    url(r'containers/add/$', 'container_add', name='container-add'),
    url(r'containers/(?P<pk>\d+)/add/$', 'container_add', name='container-add'),
    url(r'containers/(?P<pk>\d+)/edit/$', 'container_edit', name='container-edit'),
    url(r'containers/(?P<pk>\d+)/delete/$', 'container_delete', name='container-delete'),
    url(r'containers/items/add/$', 'item_add', name='item-add'),
    url(r'containers/items/(?P<pk>\d+)/add/$', 'item_add', name='item-add'),
    url(r'containers/items/(?P<pk>\d+)/edit/$', 'item_edit', name='item-edit'),
    url(r'containers/items/(?P<pk>\d+)/delete/$', 'item_delete', name='item-delete'),
    url(r'containers/items/(?P<pk>\d+)/special/off/$',
        'item_special_off',
        name='special-off'),
    url(r'containers/items/(?P<pk>\d+)/description/popup/$',
        'item_description_popup', name='item-description-popup'),
    url(r'containers/addons/add/$', 'addon_add', name='addon-add'),
    url(r'containers/(?P<pk>\d+)/addons/add/$', 'addon_add', name='addon-add'),
    url(r'containers/(?P<pk>\d+)/addons/edit/$', 'addon_edit', name='addon-edit'),
    url(r'containers/(?P<pk>\d+)/addons/list/$', 'addon_list', name='addon-list'),
    url(r'containers/addons/(?P<pk>\d+)/delete/$', 'addon_delete', name='addon-delete'),
    url(r'containers/csv/import/$', 'csv_import', name='csv-import'),
    url(r'cart/$', 'cart', name='cart'),
    url(r'cart/item/add/$', 'cart_item_add', name='cart-item-add'),
    url(r'cart/item/add/(?P<item_pk>\d+)/$', 'add_item_to_cart', name='cart-item-add'),
    url(r'cart/item/add/(?P<item_pk>\d+)/(?P<quantity>\d+)/$',
        'add_item_to_cart', name='cart-item-add'),
    url(r'cart/item/checkout/(?P<item_pk>\d+)/(?P<quantity>\d+)/$',
        'add_item_to_cart',
        {'checkout': True},
        name='cart-item-set'),
    url(r'cart/item/remove/(?P<item_pk>\d+)/$',
        'remove_item_from_cart', name='cart-item-remove'),
    # url(r'cart/item/(?P<item_pk>\d+)/addon/add/(?P<addon_pk>\d+)/$', 'add_addon_to_cart', name='cart-addon-add'),
    # url(r'cart/item/(?P<item_pk>\d+)/addon/add/(?P<addon_pk>\d+)/(?P<quantity>\d+)/$',
    #    'add_addon_to_cart', name='cart-addon-add'),

    url(r'cart/addon/add/(?P<addon_pk>\d+)/(?P<quantity>\d+)/$',
        'add_addon_to_cart', name='cart-addon-add'),
    url(r'cart/addon/checkout/(?P<addon_pk>\d+)/(?P<quantity>\d+)/$',
        'add_addon_to_cart',
        {'checkout': True},
        name='cart-addon-checkout'),
    url(r'cart/addons/add/$', 'add_addons_to_cart',
        name='add-addons-to-cart'),
    url(r'cart/addon/remove/(?P<addon_pk>\d+)/$',
        'remove_addon_from_cart', name='cart-addon-remove'),
    url(r'cart/order/$', 'order', name='order'),
    url(r'cart/order/popup/$', 'order_popup', name='cart-order-popup'),
    url(r'cart/order/success/$', direct_to_template,
        {'template': 'catalog/order_success.html'},
        name='order-success'),
    url(r'cart/cleanse/$', 'cart_cleanse', name='cart-cleanse'),
    url(r'orders/$', 'orders', name='orders'),
    url(r'orders/(?P<pk>\d+)/repeat/$', 'order_repeat',
        name='order-repeat'),
    url(r'orders/partner/$', 'orders_partner', name='orders-partner'),
    url(r'orders/partner/csv/$', 'orders_partner_csv',
        name='orders-partner-csv'),
    url(r'orders/(?P<sid>[\w\d]+)/vote/$',
        'order_vote', name='order-vote'),
    url(r'orders/vote/successfull/$', direct_to_template,
        {'template': 'catalog/order_vote_success.html'},
        name='order-vote-success'),
    url(r'orders/payment/income/$', 'order_payment_notification',
        name='order-payment-notification'),
    url(r'orders/payment/success/$', direct_to_template,
        {'template': 'catalog/payment_success.html'},
        name='payment-success'),
    url(r'orders/payment/failure/$', direct_to_template,
        {'template': 'catalog/payment_failure.html'},
        name='payment-failure'),
    url(r'cart/is/empty/$', direct_to_template,
        {'template': 'catalog/empty_cart.html'},
        name='empty-cart'),
    url(r'addons/get/(?P<pk>\d+)/$', 'get_addons',
        name='addons-get'),
    url(r'orders/(?P<pk>\d+)/update_status/(?P<status>\w+)',
        'update_order_status', name='update_order_status')
)

urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from filebrowser.sites import site

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from apps.core.shortcuts import direct_to_template
from apps.catalog.seo import Metadata
from rollyourown.seo.admin import register_seo_admin
import logging
from sorl.thumbnail.log import ThumbnailLogHandler


# handler = ThumbnailLogHandler()
# handler.setLevel(logging.ERROR)
# logging.getLogger('sorl.thumbnail').addHandler(handler)

admin.autodiscover()

register_seo_admin(admin.site, Metadata)
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'template.views.home', name='home'),
    # url(r'^template/', include('template.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^$', 'apps.catalog.views.index', name='index'),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.core.urls', namespace='core')),
    url(r'^', include('apps.accounts.urls', namespace='accounts')),
    url(r'^catalog/', include('apps.catalog.urls', namespace='catalog')),
    url(r'^blog/', include('apps.blog.urls', namespace='blog')),
    url(r'^geo/', include('apps.geo.urls', namespace='geo')),
    url(r'^json/', include('apps.jsonapp.urls', namespace='json')),
    url(r'^splash/$', direct_to_template,
        kwargs=dict(template='splash.html'))

)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': '/home/dan/git_rep/colortek/media' ,
            'show_indexes': True,
            }
        )
    )

    urlpatterns += patterns('',
        (r'^uploads/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT ,
            'show_indexes': True,
            }
        )
    )

urlpatterns += patterns('',
    url(r'^', include('apps.pages.urls')),
)

cart/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic

class Cart(models.Model):
    creation_date = models.DateTimeField(verbose_name=_('creation date'))
    checked_out = models.BooleanField(default=False, verbose_name=_('checked out'))

    class Meta:
        verbose_name = _('cart')
        verbose_name_plural = _('carts')
        ordering = ('-creation_date',)

    def __unicode__(self):
        return unicode(self.creation_date)

class ItemManager(models.Manager):
    def get(self, *args, **kwargs):
        if 'product' in kwargs:
            kwargs['content_type'] = ContentType.objects.get_for_model(type(kwargs['product']))
            kwargs['object_id'] = kwargs['product'].pk
            del(kwargs['product'])
        return super(ItemManager, self).get(*args, **kwargs)

class Item(models.Model):
    cart = models.ForeignKey(Cart, verbose_name=_('cart'))
    quantity = models.PositiveIntegerField(verbose_name=_('quantity'))
    unit_price = models.DecimalField(max_digits=18, decimal_places=2, verbose_name=_('unit price'))
    # product as generic relation
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    link_content_type = models.ForeignKey(
        ContentType, related_name='link_ct_set_for_%(class)s',
        null=True, blank=True)
    link_object_id = models.PositiveIntegerField(null=True, blank=True)
    link = generic.GenericForeignKey(
        ct_field="link_content_type",
        fk_field="link_object_id",)

    objects = ItemManager()

    class Meta:
        verbose_name = _('item')
        verbose_name_plural = _('items')
        ordering = ('cart',)

    def __unicode__(self):
        return u'%d units of %s' % (self.quantity, self.product.__class__.__name__)

    def total_price(self):
        return self.quantity * self.unit_price
    total_price = property(total_price)

    def get_quantity(self):
        if hasattr(self.product, 'get_unit_rate'):
            return self.quantity * self.product.get_unit_rate()
        return self.quantity

    # product
    def get_product(self):
        return self.content_type.get_object_for_this_type(id=self.object_id)

    def set_product(self, product):
        self.content_type = ContentType.objects.get_for_model(type(product))
        self.object_id = product.pk

    product = property(get_product, set_product)

templates/catalog/include/addon.html
{% load coretags corefilters %}
	<span class="dem">
		<span class="price">{{ addon.cost|floatformat:"-2" }}<span class="ruble">n</span></span>
		<span class="size-sel active new">
			<span class="selected"
				addition-count="{{ addon.category.threshold }}" max-count="{{ addon.category.threshold|multiply:10 }}">{{ addon.category.get_rate }}</span>
			<span class='title'>{{ addon.category.short_rate_title }}</span>
			<span class="plus"></span>
			<span class="minus"></span>
			<input type="hidden" name='quantity-{{ addon.pk }}' value="{{ addon.category.threshold }}"><!-- this field value eq span.selected content -->
		</span>
	</span>
	<label>
		<input type='checkbox' name='addons' value='{{ addon.pk }}' class="name">
		<span class="label-text">
			<!--div class='hide'>
				<input type='checkbox' name='addons' value='{{ addon.pk }}' class="name"><span class='name'>{{ addon.title }}</span>
			</div-->
			<span class="name">{{ addon.title }}</span>
		</span>
	</label>

templates/catalog/include/anonymous_user_order_info.html
<div class='anonymous user info'>
	{% if kart.service.has_online_payment %}
	<p>
		Возможен электронный платеж.<br>
		Для оплаты картой, а также получения бонусных баллов за заказ, пожалуйста, выполните
		<a href='{% url accounts:register-user %}' class="button">регистрацию</a><a href='{% url accounts:login %}' class="button">вход</a>
	</p>
	{% else %}
	<p>
		Для получения бонусных баллов, пожалуйста, выполните
		<a href='{% url accounts:register-user %}' class="button">регистрацию</a><a href='{% url accounts:login %}' class="button">вход</a>
	</p>
	{% endif %}
</div>

templates/catalog/include/border_list.html
<div class="options">
    <ul class="dish-menu">
        {% for category in serv.categories.all %}
            <li class='{{ forloop.first|yesno:"active,hidden" }}' data-id='{{ category.id }}'>
                <a href='#'>{{ category.title }}</a>
                {% if category.containers.all %}
                <ul>
                {% for container in category.get_unique_containers %}
                    <li><a href='#'>{{ container.title }}</a></li>
                {% endfor %}
                </ul>
            </li>
            {% endif %}
        {% endfor %}
    </ul>
 </div>
<script type='text/javascript'>
    $(".dish-menu li a").click(function(e){
        $(this).parent().addClass('active');
    });
</script>

templates/catalog/include/border_partner_categories.html
<div class="options">
	{% load thumbnail %}
	{% thumbnail service.logo gs.ITEM_THUMBNAIL_SIZE_TINY as image %}
    <div class="service-filter-logo">
        <a href="{% url catalog:service-page service.pk %}"><img src="{{ image.url }}" alt="{{ kart.service.service_name }}"></a>
    </div>
    {% endthumbnail %}
    <ul class="dish-menu">
        {% for category in service.get_top_containers %}
            {% if category.items.all or category.children.all %}
            <li class='{% if get_full_path|urlencode == category.get_border_url %}active{% endif %}'>
                <a href='{{ category.get_border_url }}'>{{ category.title }}</a>
                <ul>
                {% for container in category.item_children %}
                    <li class='{% if get_full_path|urlencode == container.get_border_url %}active{% endif %}'><a href='{{ container.get_border_url }}'>{{ container.title }}</a></li>
                {% endfor %}
                </ul>
            </li>
            {% endif %}
        {% endfor %}
    </ul>
 </div>
<script type='text/javascript'>
$(document).ready(function(){
    $.each($(".dish-menu li ul li.active"), function(idx, item){
        $(item).parents('li').addClass('active');
    });
});
</script>

templates/catalog/include/cart_addon.html
{% load i18n thumbnail %}
<tr class='addon'> {% trans "$." context "currency" as currency %}
    <td>{{ forloop.counter }}</td>
    <td class='title'>{{ item.product.title }}</td>
    <td class='quantity'>{{ item.quantity }}</td>
    <td class='cost'>{{ item.total_price }} {{ currency }}</td>
</tr>

templates/catalog/include/cart_item.html
{% load i18n thumbnail %}
<tr class='item'> {% trans "$." context "currency" as currency %}
    <td>{{ forloop.counter }}</td>
    {% thumbnail item.product.image global_settings.DEFAULT_THUMBNAIL_SIZE as image %}
    <td class='image'>
        <img src='{{ image.url }}' alt='{{ item.product.title }}' />{% endthumbnail %}
    </td>
    <td class='title'>{{ item.product.title }}</td>
    <td class='title'>{{ item.quantity }}</td>
    <td class='cost'>{{ item.total_price }} {{ currency }}</td>
</tr>

templates/catalog/include/catalog_categories.html
<p class="tag">
    Категория:
    {% comment %}
    {% for container in containers %}
    {{ container.title }}{% if not forloop.last %},{% endif %}
    {% endfor %}{% endcomment %}

    {% for category in service.categories.all %}
        {{ category.title }}{% if not forloop.last %},{% endif %}
    {% endfor %}

    {% if service.has_online_payment %}
    <img src="/media/img/icon/card.png" alt="" title="Оплата картой" class="tool">
    {% endif %}
</p>

templates/catalog/include/catalog_info_table.html
{% load pytils_numeral corefilters %}
<table class="price">
                <tbody><tr>
                    {% comment %}
                    {% if service.avarage_cost %}
                    <td><em>Сумма заказа:</em> <strong>{{ service.avarage_cost|default_if_none:0 }} <span class="rub">р.</span></strong></td>
                    {% endif %}
                    {% endcomment %}
                    {% if service.minimal_cost %}
                    <td><em>Мин. сумма заказа:</em> <strong>{{ service.minimal_cost|default_if_none:0|floatformat:"-2" }} <span class="rub">р.</span></strong></td>
                    {% endif %}
                    {% if service.avarage_deliver_time %}
                    <td><em>Среднее время доставки:</em> <strong>
                        {% with dt=service.get_deliver_time %}
                            {% if dt.days %}{{ dt.days }} {{ dt.days|choose_plural:"день, дня, дней" }}{% endif %}
                            {% if dt.hours %}{{ dt.hours }} {{ dt.hours|choose_plural:"час, часа, часов" }}{% endif %}
                            {% if dt.minutes %}{{ dt.minutes }} {{ dt.minutes|choose_plural:"минуты, минуту, минут" }}{% endif %}
                        {% endwith %}
                        </strong></td>
                    {% endif %}
                </tr>
                <tr>
                    {% if service.avarage_deliver_cost %}
                    <td colspan="2">
                        <em>Стоимость доставки:</em>
                        <strong>{{ service.avarage_deliver_cost|default_if_none:0|floatformat:"-2" }} <span class="rub">р.</span></strong>
                        {% if service.avarage_cost %}
                        Бесплатная доставка при заказе от <strong>{{ service.avarage_cost|floatformat:"-2" }}</strong> <span class='rub'>р.</span>
                        {% endif %}
                    </td>
                    {% endif %}
                </tr>
            </tbody></table>

templates/catalog/include/catalog_note.html
{% if service.additional %}
<div class="note">
    {{ service.additional|safe }}
</div>
{% endif %}

templates/catalog/include/items.html
{% for item in items %}
{% include "catalog/include/user_dishes_container.html" %}
{% endfor %}

templates/catalog/include/order_filters.html
{% load i18n %}{% if has_status %}
<div class="group statuses">
        {% comment %}
        <label>
        <input name='status' type="checkbox" value="not_confirmed" {% spaceless %}
        {% if 'not_confirmed' in status %}checked{% endif %}{% endspaceless %}>неподтвержденные</label>
        {% endcomment %}

        {% comment %}
        <label>
        <input name='status' type="checkbox" value="rejected" {% spaceless %}
        {% if 'rejected' in status %}checked{% endif %}{% endspaceless %}>отмененные</label>
        {% endcomment %}
        <label>
            <input name='status' type="checkbox" value="is_paid"{% spaceless %}
            {% if 'is_paid' in status %}checked{% endif %}{% endspaceless %}>
            {% trans "paid" %}</label>

        <label>
        <input name='status' type="checkbox" value="processed" {% spaceless %}
        {% if 'processed' in status %}checked{% endif %}{% endspaceless %}>
        {% trans "processed" %}</label>
        <label>
        <input name='status' type="checkbox" value="finished" {% spaceless %}
        {% if 'finished' in status %}checked{% endif %}{% endspaceless %}>{% trans "finished" %}</label>
        {% comment %}
        <label>
        <input name='status' type="checkbox" value="approved" {% spaceless %}
        {% if 'approved' in status %}checked{% endif %}{% endspaceless %}>{% trans "approved" %}</label>
        {% endcomment %}
        {% if not user.is_partner or not gs.HIDE_REJECTED_FROM_PARTNER %}
        <label>
        <input name='status' type="checkbox" value="rejected" {% spaceless %}
        {% if 'rejected' in status %}checked{% endif %}{% endspaceless %}>{% trans "rejected" %}</label>
        {% endif %}

        {% if user.is_operator %}
        <label>
        <input name='status' type="checkbox" value="approved" {% spaceless %}
        {% if 'approved' in status %}checked{% endif %}{% endspaceless %}>
        {% trans "approved" %}</label>
        {% endif %}


</div>
{% else %}
<div class="group statuses">
    <label>
        <input name='status' type="checkbox" value="is_paid"{% spaceless %}
        {% if 'is_paid' in status %}checked{% endif %}{% endspaceless %}>
        {% trans "paid" %}</label>
    {% comment %}<label>
        <input name='status' type="checkbox" value="not_confirmed" {% spaceless %}
        {% if 'not_confirmed' in status %}checked{% endif %}{% endspaceless %}>
        {% trans "not confirmed" %}</label>
<label>
        <input name='status' type="checkbox" value="processed" {% spaceless %}
        {% if 'processed' in status %}checked{% endif %}{% endspaceless %}>
        {% trans "processed" %}</label>{% endcomment %}
    {% if not user.is_partner %}
    <label>
        <input name='status' type="checkbox" value="checking" {% spaceless %}
        {% if 'checking' in status %}checked{% endif %}{% endspaceless %}>
        {% trans "checking" %}</label>
    {% endif %}
    <!--<label>
        <input name='status' type="checkbox" value="approved" {% spaceless %}
        {% if 'approved' in status %}checked{% endif %}{% endspaceless %}>
        {% trans "approved" %}</label>-->
</div>
{% endif %}

templates/catalog/include/partners.html
{% for container in containers %}
    {% include "catalog/include/user_catalog_container.html" %}
{% endfor %}

templates/catalog/include/service_page_items.html
{% load thumbnail %}
{% comment %}
    <div class="b-dish-list">
		{% if items|length < 3 %}<div class="line">{% endif %}
{% endcomment %}
		{% for item in items %}
{% comment %}
			{% if items|length > 2 %}{% cycle '<div class="line">' '' '' %}{% endif %}
{% endcomment %}
            <div class="col">
                <form method='POST' action="{% url catalog:cart-item-add %}"
                data-service-name='{{ item.container.owner.service_name }}'><div class="item"><div class="item-inner">
                    {% csrf_token %}
                    <h3>{{ item.title }}<span class="fade"></span></h3>
                    <div class="subhead">
                        {% if item.container.addons.all %}
                            <a class="supplements"
                                {# href="{% url catalog:item-description-popup item.pk %}" #}
								data-href='{% url catalog:addons-get item.container.pk %}'
                                data-container='{{ item.container.pk }}'>Добавки</a>
                        {% endif %}
                        <span class="price">{% if item.is_special_active %}
                            <s>{{ item.cost|floatformat:"-2" }}</s>&nbsp;{{ item.get_generic_cost|floatformat:"-2" }}
                        {% else %}
                            {{ item.cost|floatformat:"-2" }}
                        {% endif %}
                        <span class="ruble">n</span></span>
                    </div>
                    <div class="image" data-img="{% url catalog:item-description-popup item.pk %}">
						{% if item.image %}
							{% thumbnail item.image gs.ITEM_THUMBNAIL_SIZE_SMALL as image %}
								<img src="{{ image.url }}" alt="{{ item.title }}">
							{% endthumbnail %}
						{% else %}
							<img src="/media/img/no-content-{{ item.container.owner.service.codename }}.jpg" alt="">
						{% endif %}
                    </div>
                    <div class="order-options">
                        <div class="count">
                            <a class="minus" data-threshold='-{{ item.category.threshold }}'></a>
                            <input name='quantity' id='id_quantity' type="text" value="{{ item.category.get_rate }}">
							<span class='description'>{{ item.category.short_rate_title }}</span>
                            <input type='hidden' id='id_item' value='{{ item.pk }}' name='item' />
                        <a class="plus" data-threshold='{{ item.category.threshold }}'></a></div>
                        <input type="submit" value="Заказать" class='orderCheck'>
                    </div>
                </div></div></form><!-- /item -->
            </div>
{% comment %}
			{% if items|length > 2 %}{% cycle '' '' '</div>' %}{% endif %}
{% endcomment %}
		{% endfor %}
{% comment %}
		{% if items|length < 3 %}</div>{% endif %}
		{% if items|length > 2 and items|length|divisibleby:3 %}{% else %}</div>{% endif %}
{% endcomment %}

templates/catalog/include/user_dishes_container.html
{% load thumbnail pytils_numeral %}
{% for item in items %}
    <div class="item">
        <div class="preview">
            <div class="image" data-img="{% url catalog:item-description-popup item.pk %}">
                {% if item.image %}
                    {% thumbnail item.image gs.ITEM_THUMBNAIL_SIZE_SMALL as image %}
                        <img src="{{ image.url }}" alt="{{ item.title }}">
                    {% endthumbnail %}
                {% else %}
                    <img src="/media/img/no-content-{{ item.container.owner.service.codename }}.jpg" alt="">
                {% endif %}
            </div>
            <div class="rating">
                <!--<p class="value">10 баллов из 10</p> -->
                {% if item.container.get_votes_count > 0 %}
                <p class="comment">(<a href="{% url catalog:service-rating item.container.owner.pk %}">{{ item.container.get_votes_count }} {{ item.container.get_votes_count|choose_plural:"оценка, оценки, оценок" }}</a>)</p>
                {% endif %}
            </div>
            <div class="p-logo">
            {% if item.container.owner.logo %}
            {% thumbnail item.container.owner.logo gs.ITEM_SERVICE_THUMBNAIL_SIZE_SMALL as image %}
                <a href="{% url catalog:service-page item.container.owner.pk %}"><img src="{{ image.url }}" alt="{{ item.container.owner.service_name|default_if_none:item.container.owner.username }}"></a>{% endthumbnail %}
            {% else %}
                <a href="{% url catalog:service-page item.container.owner.pk %}">
                    <img src="/media/img/no-logo.png"
                        alt="{{ item.container.owner.service_name|default_if_none:item.container.owner.username }}">
                </a>
            {% endif %}
            </div>
        </div>
        <div class="preview-text">
            <!--<a class="supplements" href="#">Добавки</a>-->
            <h3>{{ item.title }}</h3>
            <p class="ingredient">
                {{ item.description|safe }}
                {% if item.container.owner.has_online_payment %}
                    <img src="/media/img/icon/card.png" alt="" title="Оплата картой" class="tool">
                {% endif %}
            </p>
            <table class="price">
                <tbody><tr>
                    <td><em>Мин. сумма заказа:</em> <strong>{{ item.container.owner.minimal_cost|default_if_none:0|floatformat:"-2" }} <span class="rub">р.</span></strong></td>
                    <td><em>Стоимость доставки:</em> <strong>{{ item.container.owner.avarage_deliver_cost|default_if_none:0 }} <span class="rub">р.</span></strong></td>

                </tr>
                <tr>
                    <td colspan="2"><a href="{% url catalog:service-page item.container.owner.pk %}">{{ item.container.owner.service_name|default_if_none:item.container.owner.username }}</a> / Категория:
                    {% if item.container.container %}{{ item.container.container.title }},{% endif %}
                    {{ item.container.title }}
                    {% if item.is_special_active %}
                        <br>
                        <strong>Акция до: {{ item.special_expires|date:"d.m.Y" }}</strong>
                    {% endif %}
                    </td>
                </tr>
            </tbody></table>
            <div class="order-action">
                <form action='{% url catalog:cart-item-add %}' method='POST' class=''
                    data-service-name='{{ item.container.owner.service_name }}'>
                    {% csrf_token %}
                    <input class='purchase orderCheck' type="submit" value="Заказать" data-id='{{ item.pk }}'>
                    <div class="params">
                        {% if item.mass %}<span class='size'>{{ item.mass }} гр. /</span>{% endif %}
                        Цена: <strong>
                        {{ item.get_generic_cost|floatformat:"-2" }}
                        <span class="ruble">n</span></strong>
                        {% if item.mass %}
                        {% endif %}
                    </div>
                    <div class="count">
                        <a class="minus" data-threshold='-{{ item.category.threshold }}'></a>
                        <input name='quantity' id='id_quantity' type="text" value="{{ item.category.get_rate }}">
                        <input name='item' value='{{ item.pk }}' type='hidden'>
                        <a class="plus" data-threshold='{{ item.category.threshold }}'></a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endfor %}