apps/accounts/urls.py
from django.conf.urls import patterns, include, url
from apps.core.shortcuts import direct_to_template

urlpatterns = patterns('apps.accounts.views',
    url(r'login/$', 'login', name='login'),
    url(r'logout/$', 'logout', name='logout'),
    url(r'profile/$', 'profile', name='profile'),
    url(r'profile/bonuses/', 'profile_bonuses', name='profile-bonuses'),
    url(r'profile/edit/$', 'profile_edit', name='profile-edit'),
    url(r'profile/edit/organization', 'profile_edit_org',
        name='profile-edit-org'),
    url(r'profile/delivercost/(?P<pk>\d+)/delete/$',
        'deliver_cost_delete', name='deliver-cost-delete'),
    url(r'profile/set/coordinates/$',
        'set_coordinates', name='set-coordinates'),
    url(r'profile/purge/coordinates/$',
        'purge_coordinates', name='purge-coordinates'),
    url(r'profile/contact/phone/(?P<pk>\d+)/delete/$',
        'profile_contact_phone_delete',
        name='profile-contact-phone-delete'),
    url(r'profile/contact/email/(?P<pk>\d+)/delete/$',
        'profile_contact_email_delete',
        name='profile-contact-email-delete'),    
    url(r'user/register/$', 'register_user', name='register-user'),
    url(r'partner/register/$', 'register_partner', name='register-partner'),
    url(r'partner/alter/schedule/$', 'alter_schedule', name='alter-schedule'),
    url(r'register/success/', direct_to_template,
        {'template': 'accounts/register_success.html'},
        name='register-success'),
    #invites
    url(r'^invite/$', 'invite', name='invite'),
    url(r'^invite/register/success/$', direct_to_template,
        {'template': 'accounts/invite_register_success.html'},
        name='invite-register-success'),
    url(r'^invite/success/$', direct_to_template,
        {'template': 'accounts/invite_success.html'},
        name='invite-success'),
    url(r'^invite/register/(?P<sid>[\w\d]+)/$',
        'invite_register', name='invite-register'),
    url(r'^account/(?P<sid>[\w\d\_-]+)/verify/$',
        'account_verify', name='account-verify'),
    url(r'account/password/(?P<sid>[\w\d]+)/restore/$',
        'password_restore',
        name='password-restore'),
    url(r'account/password/restore/initiate/$',
        'password_restore_initiate',
        name='password-restore-initiate'),

    #end of invites
)

urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from filebrowser.sites import site

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from apps.core.shortcuts import direct_to_template
from apps.catalog.seo import Metadata
from rollyourown.seo.admin import register_seo_admin
import logging
from sorl.thumbnail.log import ThumbnailLogHandler


# handler = ThumbnailLogHandler()
# handler.setLevel(logging.ERROR)
# logging.getLogger('sorl.thumbnail').addHandler(handler)

admin.autodiscover()

register_seo_admin(admin.site, Metadata)
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'template.views.home', name='home'),
    # url(r'^template/', include('template.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^$', 'apps.catalog.views.index', name='index'),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.core.urls', namespace='core')),
    url(r'^', include('apps.accounts.urls', namespace='accounts')),
    url(r'^catalog/', include('apps.catalog.urls', namespace='catalog')),
    url(r'^blog/', include('apps.blog.urls', namespace='blog')),
    url(r'^geo/', include('apps.geo.urls', namespace='geo')),
    url(r'^json/', include('apps.jsonapp.urls', namespace='json')),
    url(r'^splash/$', direct_to_template,
        kwargs=dict(template='splash.html'))

)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': '/home/dan/git_rep/colortek/media' ,
            'show_indexes': True,
            }
        )
    )

    urlpatterns += patterns('',
        (r'^uploads/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT ,
            'show_indexes': True,
            }
        )
    )

urlpatterns += patterns('',
    url(r'^', include('apps.pages.urls')),
)

apps/accounts/models.py
# coding: utf-8
from datetime import datetime, timedelta

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils.translation import ugettext_lazy as _

from django.contrib.auth.models import User

from apps.accounts.managers import VerificationManager

import caching.base



WEEKDAY_CHOICES = (
    (1, _("Mon")),
    (2, _("Tue")),
    (3, _("Wed")),
    (4, _("Thu")),
    (5, _("Fri")),
    (6, _("Sat")),
    (7, _("Sun")),
)


class ContactPhoneType(models.Model):
    title = models.CharField(_("title"), max_length=32, unique=True)

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = _("Contact phone type")
        verbose_name_plural = _("Contact phone types")


class ContactPhone(models.Model):
    phone = models.CharField(_("phone"), max_length=21)
    type = models.ForeignKey(
        ContactPhoneType, related_name='phone_type_set', default=1,
        verbose_name=_('phone type'))
    user = models.ForeignKey(
        User, related_name='phone_user_set',
        verbose_name=_("phone user"))

    def __unicode__(self):
        return "%(type)s: %(phone)s [%(user)s]" % {
            'type': self.type.title,
            'phone': self.phone,
            'user': self.user.username
        }

    class Meta:
        verbose_name = _("Contact phone")
        verbose_name_plural = _("Contact phones")


class ContactEmail(models.Model):
    email = models.EmailField(_("email"))
    user = models.ForeignKey(User, related_name='email_user_set')

    def __unicode__(self):
        return '%s [%s]' % (self.email, self.user.username)

    class Meta:
        verbose_name = _("Contact email")
        verbose_name_plural = _("Contact emails")


class Schedule(models.Model):
    """ partner working schedule,
    contains working days with its time ranges
    """
    user = models.ForeignKey('auth.User', related_name='schedule_user_set')

    @property
    def days(self):
        return self.timenday_schedule_set

    def __unicode__(self):
        return unicode(_("%s schedule") % self.user.username)

    class Meta:
        verbose_name = _("Schedule")
        verbose_name_plural = _("Schedules")


class TimeNDay(caching.base.CachingMixin, models.Model):
    """ describes working time for given day """
    weekday = models.IntegerField(
        _("week day"),
        validators=[
            MinValueValidator(1),  # 1 means monday
            MaxValueValidator(7)  # 2 means sunday
        ],
        choices=WEEKDAY_CHOICES
    )
    since = models.TimeField(_("since"))
    until = models.TimeField(_("until"))
    schedule = models.ForeignKey(
        'accounts.Schedule', related_name='timenday_schedule_set',
        verbose_name=_("schedule"))
    is_active = models.BooleanField(
        _('is active?'),
        help_text=_("marks if this schedule point is active"),
        default=True
    )

    objects = caching.base.CachingMixin()

    def __unicode__(self):
        return ("[{user}] {weekday}, {since} - {until}").format(
            user=self.schedule.user.username, weekday=self.weekday,
            since=self.since, until=self.until
        )

    class Meta:
        verbose_name = _("Time and day")
        verbose_name_plural = _("Time and days")


class DeliverCost(models.Model):
    user = models.ForeignKey(
       User, related_name='deliver_cost_user_set'
    )
    min = models.PositiveIntegerField(
        _("min"), default=0,
        help_text=_("min border value in killometers")
    )
    max = models.PositiveIntegerField(
        _("max"), default=5,
        help_text=_("max border value in killometers")
    )
    cost = models.DecimalField(
        _("cost"), help_text=_("Deliver cost for this distance range"),
        max_digits=10, decimal_places=2,
    )

    def __unicode__(self):
        return "%s [%s km to %s km]" % (self.cost, self.min, self.max)

    class Meta:
        verbose_name = _("Deliver cost")
        verbose_name_plural = _("Deliver costs")


class Invite(models.Model):
    is_expired = models.BooleanField(
        _("is expired?"), default=False)
    expire_date = models.DateTimeField(
        _("expire date"), help_text=_("date and time when invite is expired"),
        default=datetime.now() + timedelta(days=7)
    )
    created_on = models.DateTimeField(
        _("created on"), help_text=_("created date of invitation"),
        default=datetime.now, auto_now_add=True
    )
    updated_on = models.DateTimeField(
        _("updated on"), help_text=_("date when this was updated last time"),
        default=datetime.now, auto_now=True
    )
    sender = models.ForeignKey(
        User,
        related_name='invite_sender_user_set', null=True,
        verbose_name=_("sender")
    )
    reciever = models.ForeignKey(
        User,
        related_name='invite_reciever_user_set', null=True,
        blank=True,
        verbose_name=_("reciever")
    )
    email = models.EmailField(
        _("Email"), help_text=_("Friend email"), null=True,
        unique=True
    )
    sid = models.CharField(
        _("SID"), help_text=_("SpecialID for registration"),
        max_length=128
    )
    is_verified = models.BooleanField(
        _("is verified?"), help_text=_("shows if user is verified"),
        default=False)

    def __unicode__(self):
        return "%s [%s]" % (self.sender.username, self.email)

    class Meta:
        verbose_name = _("Invite")
        verbose_name_plural = _("Invites")
        ordering = ['-created_on', '-updated_on']


class Verification(models.Model):
    is_processed = models.BooleanField(
        _("is processed?"), default=False,
    )
    sid = models.CharField(max_length=512, unique=True)
    user = models.ForeignKey(
        User, related_name='verification_user_set',
        null=True, blank=True
    )
    is_verified = models.BooleanField(
        _('is verified?'), default=False
    )

    objects = VerificationManager()

    def __unicode__(self):
        return self.user.username

    class Meta:
        verbose_name = _("Verification")
        verbose_name_plural = _("Verification")


from apps.accounts.signals import setup_signals
setup_signals()

templates/accounts/include/partner_profile.html
{{ usr.username }}
partner profile

templates/accounts/include/partner_profile_edit.html
<div class="partners">{% load coretags corefilters %}
    <div class="menu">
        <div class="b-inner">
            <div class="content">
                <ul>
                    <li class="active">мои настройки</li>
                    <li><a href="{% url catalog:service-orders %}">Мои заказы</a></li>
                    <li><a href="{% url catalog:container-list %}">Мои товары</a></li>
                    <li><a href="{% url catalog:service-partner-specials user.pk %}">Мои акции</a></li>
                    <li><a href='{% url catalog:csv-import %}'>Импортирование базы</a></li>
                </ul>
                <div class="Clear"></div>
            </div>
        </div>
    </div>
    <div class="b-inner">
        <div class="content">
            <div class="header">
                <div class="rText">Здесь вы можете редактировать данные своего профиля:<br>логин, пароль, адреса и т.д.</div>
                <div class="Clear"></div>
            </div>

            <p class="commission-info right">Ваша комиссия: {{ user.commission|multiply:gs.HUNDRED|safe|floatformat }} %</p>

            <div class="b-content-filter">
                {% if user.is_partner %}
                <a href="{% url accounts:profile-edit-org %}"><span>Данные об организации</span></a>
                <a class="active"><span>Данные о контактном лице</span></a>
                {% else %}
                <a class="active"><span>Данные о пользователе</span></a>
                {% endif %}
                <a href='{% url accounts:set-coordinates %}'>Привязка к карте</a>
            </div>

            {% if success %}
            <div class='info'>
                <h3>Профиль успешно сохранен</h3>
            </div>
            {% endif %}
            {% if form.errors %}
                {{ form.errors }}
            {% endif %}

            <form action="" method="POST" action='{% url accounts:profile-edit %}' id='update-form'>
                {% csrf_token %}
                <div class="contentform editform">
                    <h4>Доступ в личный кабинет</h4>
                    <!-- it's like shoot in my face, why are you doing this?? -->
                    <div class="line">
                        <span class="name">логин</span>
                        <input type="text" value="{{ user.username }}" name='username' id='id_username'>
                    </div>
                    <div class="line">
                        <span class="name">пароль</span>
                        <input type="password" value="" name='password' id='id_password'>
                    </div>
                    <h4>Контактные данные</h4>
                    <div class="line">
                        <span class="name">Фамилия</span>
                        <input type="text" value="{{ user.last_name }}" name='last_name' id='id_last_name'>
                    </div>
                    <div class="line">
                        <span class="name">Имя</span>
                        <input type="text" value="{{ user.first_name }}" name='first_name' id='id_first_name'>
                    </div>
                    <div class="line">
                        <span class="name">Отчество</span>
                        <input type="text" value="{{ user.middle_name|default_if_none:"" }}" name='middle_name' id='id_middle_name'>
                    </div>
                    <div class="line">
                        <span class="name">E-mail</span>
                        <input type="text" value="{{ user.email }}" name='email' id='id_email'>
                    </div>
                    {% comment %}
                    {% get_instances 'accounts.contactphonetype' as phone_types %}
                    {% for phone in user.phones.all %}
                    <div class="line">
                        <span class="name">Контактный телефон</span>
                        <div class="phone">
                            <div class="clone">
                                <div class="cusel   cuselScrollArrows" id="cuselFrame-cuSel-0" style="width:111px" tabindex="0"><div class="cuselFrameRight"></div><div class="cuselText">{{ phone_types.0.title }}</div><div class="cusel-scroll-wrap" style="display: none;"><div class="cusel-scroll-pane" id="cusel-scroll-cuSel-0">
                                    {% for type in phone_types %}
                                    <span val="{{ type.pk }}" class="cuselActive">{{ type.title }}</span>
                                    {% endfor %}
                                </div></div><input type="hidden" id="cuSel-0" name="" value="{{ phone_types.0.pk }}" name='contact_phone_type' id='{{ phone.pk }}'></div>
                                <!--<span class="cc">+7</span>-->
                                <!--<input type="text" value="921" class="code">-->
                                <input type="text" value="{{ phone.phone }}"
                                    class="number" name='contact_phone' id='id_contact_phone_{{ phone.pk }}'>
                            </div>
                            <a href="#" class="add">добавить</a>
                        </div>
                    </div>
                    {% endfor %}
                    {% endcomment %}

                    {% get_instances 'accounts.contactphonetype' as phone_types %}
                    {% if user.phones.all %}
                    {% for phone in user.phones.all %}
                    <div class="line">
                        <span class="name">Контактный телефон</span>
                        <div class="phone">
                            <div class="clone">
								{% comment %}
                                <div class="cusel   cuselScrollArrows" id="cuselFrame-cuSel-0" style="width:111px" tabindex="0"><div class="cuselFrameRight"></div><div class="cuselText">{{ phone_types.0.title }}</div><div class="cusel-scroll-wrap" style="display: none;"><div class="cusel-scroll-pane" id="cusel-scroll-cuSel-0">
                                    {% for type in phone_types %}
                                    <span val="{{ type.pk }}" class="cuselActive">{{ type.title }}</span>
                                    {% endfor %}
                                </div></div><input type="hidden"
                                    value="{{ phone_types.0.pk }}"
                                    name='contact_phone_type' id='contact_phone_type_{{ phone.pk }}'></div>
								{% endcomment %}
								<select name='contact_phone_type'>
									{% for type in phone_types %}
                                    <option value="{{ type.pk }}" {% if phone.type == type %}selected='selected'{% endif %}>{{ type.title }}</option>
                                    {% endfor %}
								</select>
                                <input type="text" value="{{ phone.phone }}" class="number" name='contact_phone' id='id_contact_phone_{{ phone.pk }}'>
                            </div>
                            <a href="#" class="add">добавить</a>
                            <a class='del'
                                href='{% url accounts:profile-contact-phone-delete phone.pk %}'>удалить</a>
                        </div>
                    </div>
                    {% endfor %}
                    {% else %}
                    <div class="line">
                        <span class="name">Контактный телефон</span>
                        <div class="phone ">
                            <div class="clone">
								{% comment %}
                                <div class="cusel cuselScrollArrows" id="cuselFrame-cuSel-0" style="width:111px" tabindex="0"><div class="cuselFrameRight"></div><div class="cuselText">{{ phone_types.0.title }}</div><div class="cusel-scroll-wrap" style="display: none;"><div class="cusel-scroll-pane" id="cusel-scroll-cuSel-0">
                                    {% for type in phone_types %}
                                    <span val="{{ type.pk }}" class="cuselActive">{{ type.title }}</span>
                                    {% endfor %}
                                </div></div><input type="hidden"
                                    value="{{ phone_types.0.pk }}" name='contact_phone_type'></div>
								{% endcomment %}
								<select name='contact_phone_type'>
									{% for type in phone_types %}
                                    <option value="{{ type.pk }}">{{ type.title }}</option>
                                    {% endfor %}
								</select>
                                <input type="text" value="" class="number" name='contact_phone'>
                            </div>
                            <a href="#" class="add">добавить</a>
                        </div>
                    </div>
                    {% endif %}
                    
                    {% if user.emails.all %}
                    {% for email in user.emails.all %}
                    <div class="line">
                        <span class="name">Дополнительный e-mail</span>
                        <div class="phone">
                            <div class="clone">
                                <input type="text" value="{{ email.email }}" class="number" name='contact_email' id='id_contact_email_{{ email.pk }}'>
                            </div>
                            <a href="#" class="add">добавить</a>
                            <a class='del'
                                href='{% url accounts:profile-contact-email-delete email.pk %}'>удалить</a>
                        </div>
                    </div>
                    {% endfor %}
                    {% else %}
                    <div class="line">
                        <span class="name">Дополнительный e-mail</span>
                        <div class="phone ">
                            <div class="clone">
                                <input type="text" value="" class="number" name='contact_email'>
                            </div>
                            <a href="#" class="add">добавить</a>
                        </div>
                    </div>
                    {% endif %}

                    {% if user.is_partner %}
                    <div class="line">
                        <span class="name">номер для смс-уведомлений</span>
                        <div class="phone">
                            <!--<span class="cc">+7</span>
                            <input type="text" value="921" class="code"> -->
                            <input type="text" value="{{ user.phone }}" class="number" name='phone' id='id_phone'>
                        </div>
                    </div>
                    {% endif %}
                    <div class="line submit">
                        <input type="submit" value="Сохранить">
                    </div>

                </div>
            </form>


        </div>
    </div>

{% if user.is_partner %}
<script src='/media/js/tiny_mce/tiny_mce_src.js'></script>
<script src='/media/js/textareas.js'></script>
<script type='text/javascript'>
{% endif %}
{% if form.errors %}
    form = {
        errors: {
            {% for error in form.errors %}"{{ error }}": '{{ form.errors|get:error }}' {% if forloop.last %},{% endif %}{% endfor %}
        }
    }
    var updateErrorFields = function(frm){
        for (item in form.errors){
            blk = $(form.errors[item]);
            //console.log(blk);
            insert_before_blk = $($("#id_" + item).parents('.line').children()[0]);
            blk.insertBefore(insert_before_blk);
        }
    }
    $(document).ready(function(){
        updateErrorFields('#update-form');
    });
{% endif %}
</script>

</div>

templates/accounts/include/time_options.html
<option value="08:00"{% if tm|time:"H:i" == '08:00' %}selected{% endif %}>08:00</option>
<option value="09:00"{% if tm|time:"H:i" == '09:00' %}selected{% endif %}>09:00</option>
<option value="10:00"{% if tm|time:"H:i" == '10:00' %}selected{% endif %}>10:00</option>
<option value="11:00"{% if tm|time:"H:i" == '11:00' %}selected{% endif %}>11:00</option>
<option value="12:00"{% if tm|time:"H:i" == '12:00' %}selected{% endif %}>12:00</option>
<option value="13:00"{% if tm|time:"H:i" == '13:00' %}selected{% endif %}>13:00</option>
<option value="14:00"{% if tm|time:"H:i" == '14:00' %}selected{% endif %}>14:00</option>
<option value="15:00"{% if tm|time:"H:i" == '15:00' %}selected{% endif %}>15:00</option>
<option value="16:00"{% if tm|time:"H:i" == '16:00' %}selected{% endif %}>16:00</option>
<option value="17:00"{% if tm|time:"H:i" == '17:00' %}selected{% endif %}>17:00</option>
<option value="18:00"{% if tm|time:"H:i" == '18:00' %}selected{% endif %}>18:00</option>
<option value="19:00"{% if tm|time:"H:i" == '19:00' %}selected{% endif %}>19:00</option>
<option value="20:00"{% if tm|time:"H:i" == '20:00' %}selected{% endif %}>20:00</option>
<option value="21:00"{% if tm|time:"H:i" == '21:00' %}selected{% endif %}>21:00</option>
<option value="22:00"{% if tm|time:"H:i" == '22:00' %}selected{% endif %}>22:00</option>
<option value="23:00"{% if tm|time:"H:i" == '23:00' %}selected{% endif %}>23:00</option>
<option value="23:59"{% if tm|time:"H:i" == '23:59' %}selected{% endif %}>24:00</option>
<option value="00:00"{% if tm|time:"H:i" == '00:00' %}selected{% endif %}>00:00</option>
<option value="01:00"{% if tm|time:"H:i" == '01:00' %}selected{% endif %}>01:00</option>
<option value="02:00"{% if tm|time:"H:i" == '02:00' %}selected{% endif %}>02:00</option>
<option value="03:00"{% if tm|time:"H:i" == '03:00' %}selected{% endif %}>03:00</option>
<option value="04:00"{% if tm|time:"H:i" == '04:00' %}selected{% endif %}>04:00</option>
<option value="05:00"{% if tm|time:"H:i" == '05:00' %}selected{% endif %}>05:00</option>
<option value="06:00"{% if tm|time:"H:i" == '06:00' %}selected{% endif %}>06:00</option>
<option value="07:00"{% if tm|time:"H:i" == '07:00' %}selected{% endif %}>07:00</option>

templates/accounts/include/user_profile.html
<div class='well user profile'> {% load i18n %}
    <div class='username'>
        <span class='label'>{% trans "Username" %}</span>
        <span class='content'>{{ user.username }}</span>
   </div>
    <div class="real-name">
        <span class="label">{% trans "Real name" %}</span>
        <span class="content">{{ user.get_real_name }}</span>
    </div>
    <div class="email">
        <span class="label">{% trans "Email" %}</span>
        <span class="content">{{ user.email }}</span>
    </div>
    <div class="phone">
        <span class="label">{% trans "Phone" %}</span>
        <span class="content">{{ user.phone }}</span>
    </div>
    <br />
    <a class='btn btn-success' href='{% url accounts:profile-edit %}'>{% trans "Edit profile" %}</a>
</div>